FROM gradle:7-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle installDist

FROM openjdk:11
EXPOSE 8080
EXPOSE 8443

RUN mkdir /app
COPY --from=build /home/gradle/src /app
CMD ["/app/build/install/ru.chatium.chatiumapp/bin/ru.chatium.chatiumapp"]