version: "3.9"
services:
  web:
    build: .
    ports:
      - "8443:8443"
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s